### ISSUE TITLE
Bidi Isolation and Isolating Controls in Strings editorial comments

### ISSUE THREAD

**Issue by r12a** [w3c/string-meta#17]
https://w3c.github.io/string-meta/#controlsInStrings

> Do not produce or require bidi isolating controls by default.

This seems way to vague to me. Isolation is something that's pretty essential when the string is positioned in its target location: i think we're just saying that you shouldn't attach _isolating directional formatting characters_ to strings in order to apply isolation. Rather the target context should apply isolation around any inserted string.

> HTML5 [HTML5] introduced isolation at the element level by default. 

Well, it only applies to an inline element if you have a `dir` attribute or use `bdi`. Not all inline elements are isolating, as that sentence suggests.

> Use of strings in a plain text or other display context cannot be guaranteed the isolating behavior provided by HTML.

... unless directional formatting control characters are used in the target location, so that they end up surrounding the inserted string.

> The advantages of using isolating controls around a string ...

I'm assuming that this means adding the formatting characters to the string itself, rather than adding to the target location.

We actually have a section that discusses most of the stuff in this section: [3.2.2.4 Paired formatting characters](https://w3c.github.io/string-meta/#paired) There should be some cross-referencing between the two.

**Comment by aphillips** [comment]
have our changes addressed this?

**Comment by r12a** [comment]
Closing this, as i think it's stale.
