### ISSUE TITLE
Is script covered?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/string-meta#2]
I am wondering if adding script information is in the scope of this document.  In other words, does "language metadata" cover script as well?   If we use RFC 5646, we can certainly include script information.  But some explicit wording about script would be nice.

Most international metadata formats provide a single representation for each 
metadata piece.  Japan has often added a kana representation for such a 
a representation.  This is localization and will not interwork with non-Japanese 
metadata repositories.

It would be nice if this document explicitly allows script metadata and recommends future metadata formats to allow multiple representations for each metadata piece.

**Comment by aphillips** [comment]
@murata0204 This is a good point. We don't make specific mention of script as separate metadata, although there is some mention of additional metadata needs:

> A well-internationalized catalog would include additional metadata to what is shown above. That is, for each of the fields containing natural language text, such as the title and authors fields, there should be language and base direction information stored as metadata. (There may be other values as well, such as pronunciation metadata for sorting East Asian language information.) These metadata values are used by consumers of the data to influence the processing and enable the display of the items in a variety of ways.

I don't know that defining a specific script field is that useful as compared to fields for specific uses. For example, a pronunciation field to contain yomi (and usually used for linguistic or dictionary sorting of kanji strings). This field could have a script associated with it such as `Jpan` or `Hrkt`.

Of course, some languages need the script subtag in the language tag, e.g. `zh-Hans` vs. `zh-Hant` or `az-Cyrl` vs. `az-Latn` vs. `az-Arab`.

Do you have something else specific in mind? Can you suggest text?

**Comment by aphillips** [comment]
The section 'Script Subtags' should address this.

**Comment by r12a** [comment]
Closing the issue as resolved. Reopen if you disagree.
