### ISSUE TITLE
section 4 (approaches for language) and section 5 (approaches for base direction) identify recommended practices differently

### ISSUE THREAD

**Issue by dbaron** [w3c/string-meta#22]
Section 4 (approaches for language) and section 5 (approaches for base direction) identify which practices are recommended or not in very different ways.  Section 4 has a ✪ in the section heading to indicate which one is the recommended practice (although it doesn't have a ✪ for that section's subsection), whereas section 5 has text under each section heading saying one of:
* "This approach is NOT recommended.",
* "This approach is Recommended.", or
* "This approach is only recommended as a workaround for situations that prevent the use of metadata."

I think the annotations in section 5 are considerably clearer... and it does feel odd that they're not consistent since I think that makes it less clear what the document is recommending.

(I got here from w3ctag/design-reviews#178.)

**Comment by dbaron** [comment]
I think this is also a bit confusing because the recommended approach in section 4 is actually an approach that addresses *both* language and base direction -- and it's not explicitly repeated in section 5.

**Comment by aphillips** [comment]
I have merged sections 4 and 5 together and regularized their structure. The origin of this document is that Richard and I made a Frankendocument out of two very different ones we separately authored and then, in the past couple weeks, have been massively reorganizing. Hopefully the structural problems are now somewhat rectified. There are still some gaps in examples, pro/con text, and probably the list of BPs themselves. If you could have a look and see if we're on the right track, though, I'd appreciate it.

**Comment by aphillips** [comment]
Further edits (many many many further edits) have been committed. I'm going to close this comment as obsolete. But feel free to reopen if needed.
