### ISSUE TITLE
interpreted HTML typo?

### ISSUE THREAD

**Issue by aphillips** [w3c/string-meta#24]
The example in section 3.2.4 of the 2019-02-07 draft shows:

"<span dir='ltr'>one שתיים three</span>"

Should it show the `dir` with a value of `rtl` for consistency with the above examples?

**Comment by r12a** [comment]
That _makes_ it consistent with the above examples.  (You had changed some of them, i believe incorrectly, but i changed them back. They are all approached from the pov of bidi text in LTR, then go on to compare with RTL.)

**Comment by aphillips** [comment]
A close reading shows that I'm wrong. When I previously changed the example, though, it helped illustrate RTL usage I think a bit better. The phrase "HTML and CSS" in Arabic is *in* Arabic and should have a reversed order, even though most of the characters are Latin script. But you're right that your current examples are LTR and I agree that "one TWO three" is less ambiguous an example.
