### ISSUE TITLE
(editorial) is it a hashtag?

### ISSUE THREAD

**Issue by iherman** [w3c/string-meta#28]
In [§3.2.2](https://w3c.github.io/string-meta/#initial-latin) the text says 'her a hashtag' but the text just says "bidi" not "#bidi". Or does the Hebrew word means hashtag? Not clear from the text...

**Comment by aphillips** [comment]
I was wondering the same thing myself. I think it's a leftover, since the hashtag would be an example of "opening punctuation" (vs. "final punctuation" in the previous section--which might need to say "opening and final punctuation"??)

**Comment by r12a** [comment]
It is indeed a hangover from previous text. Changed to 'such as a hashtag'. 

I also worked on the examples.

Please check at https://w3c.github.io/string-meta/#initial-latin

**Comment by iherman** [comment]
Thanks!
