### ISSUE TITLE
(editorial) Why is the ordering incorrect?

### ISSUE THREAD

**Issue by iherman** [w3c/string-meta#29]
Example in [§3.2.3](https://w3c.github.io/string-meta/#bidirectional-text-ordering) claims that the second display of text in an RTL setting is incorrect. Is it? I am not sure why; I have the feeling that it _is_ correct in an RTL setting, but it of course creates a different entry in case the strings are ordered.

**Comment by aphillips** [comment]
That is probably something we should explain better. You're correct, of course, that the reordering here is "correct" in either direction, depending on the base direction expected by the reader. The problem occurs when the reordering violates expectations or results in words landing out of context. 

I use different examples on an internal educational page:

```
size: large
الحجم: كبير

amazon.com/م1ك/ق2ف
amazon.com/م1ك/ق2ف  <- looks very different in RTL
```

Maybe here it is enough to say that the order is merely different (leave correctness out of it) while making clear that this kind of reordering can have bad effects? 

Richard, what say you?

**Comment by r12a** [comment]
Thanks for spotting this @iherman. Perhaps the new text is better?
https://w3c.github.io/string-meta/#bidirectional-text-ordering

**Comment by iherman** [comment]
Thanks @r12a this is much clearer. 

Except that I cannot figure out how on Earth that text with the spans ended up the way it shows on RTL, but I believe you:-) If it is possible to add a note with a hints on how that happened, that would be even better. Of course, the main subliminal message is: "if you are not careful, it can become incredibly messy so watch out!", and this messages come through loud and clear...

**Comment by r12a** [comment]
Don't believe me – your browser is doing it ;-)

I added a short explanation at the bottom of  https://w3c.github.io/string-meta/#bidirectional-text-ordering

**Comment by iherman** [comment]
Thanks for the additional note, I can see what is happening...

My original comment, whereby

> the main subliminal message is: "if you are not careful, it can become incredibly messy so watch out!"

still holds :-)
