### ISSUE TITLE
Illustration missing?

### ISSUE THREAD

**Issue by iherman** [w3c/string-meta#30]
At the end of [§4.2.1](https://w3c.github.io/string-meta/#how-it-works-0) the text says:

> Consumers would need to understand how to read the metadata sent with a string, and would need to apply first-strong heuristics in the absence of metadata.
>
> illustrates how this could be implemented.

Is there a missing illustration?

**Comment by aphillips** [comment]
Addressed in version 2019-02-18. There was a link in the previous version that respec failed to stringify properly---probably because the link was also broken. I removed the sentence while incorporating text from elsewhere. Please reopen if needed.

**Comment by iherman** [comment]
Indeed, closing
