### ISSUE TITLE
RDF datatype example

### ISSUE THREAD

**Issue by iherman** [w3c/string-meta#31]
[§4.7.1](https://w3c.github.io/string-meta/#dir-approach-new-datatype) just says "it is not recommended". I think the text can be misunderstood. Indeed, the text currently reads as if this was a wrong idea in general, but I do not think it is.

Indeed, _if_ RDF is (finally...) extended by adding base direction to the text literals then the syntax used in (Example 2)[https://w3c.github.io/string-meta/#example-2] _is_ a perfectly feasible syntax. I.e., from an RDF point of view, it is of course correct that this cannot be used today, but it _would be_ a correct solution if defined and, therefore implemented, generally. 

(Obviously, that would then be the basis of a proper solution for JSON-LD, too.)

**Comment by aphillips** [comment]
I agree. A better statement would probably be "less feasible alternative" or even "not currently available"

**Comment by iherman** [comment]
I would opt for a "not currently available" with possibly a note saying that this approach, or something similar, may be adopted later.

I hope to be abke to rause this i18n issue of RDF at the relevant W3C workshop in Berlin in a few weeks, b.t.w.

**Comment by r12a** [comment]
I made the change. Please check.
https://w3c.github.io/string-meta/#dir-approach-new-datatype

**Comment by iherman** [comment]
Thanks! Closing.
