### ISSUE TITLE
TAG discussion pointer

### ISSUE THREAD

**Issue by r12a** [w3c/string-meta#4]
The issue [Serialization of natural language in data formats such as JSON](https://github.com/w3ctag/design-reviews/issues/178) is not reachable by our notification system. 

In lieu, this issue serves as a handy pointer to their issue location, and a reminder that that issue is there.

**Comment by tobie** [comment]
For reference, related WebIDL issue: heycam/webidl#358.

**Comment by xfq** [comment]
Both the TAG issue and the WebIDL PR have been closed. Should we close this?

**Comment by xfq** [comment]
Closing per https://www.w3.org/2024/07/18-i18n-minutes.html#t10
